name: Fetch Scores

on:
  schedule:
    - cron: "0 * * * *" # stündlich
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install deps
        run: npm install
      - name: Run fetch script
        run: node fetch.mjs
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-results
          path: public
