name: Fetch SIHF Results

on:
  workflow_dispatch:   # manuell auslösbar
  schedule:
    - cron: "0 */6 * * *"   # alle 6 Stunden

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Ensure curl available
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Run fetch script
        run: |
          node fetch.mjs

      - name: Upload artifacts (results + debug)
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            public/results.json
            public/debug.txt
            public/raw-results.txt
