name: Fetch Results

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run fetch
        run: node fetch.mjs

      - name: Commit results
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add public/results.json public/raw-results.json public/debug.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update results [skip ci]"
            git push --force origin HEAD:main
          else
            echo "No changes"
          fi
